# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoveMovie' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'AFNetworking', '~> 3.0'
  pod 'Alamofire', '~> 4.4'
  pod 'SwiftyJSON', '~> 3.1'
  pod 'AnimatedCollectionViewLayout', '~> 0.3'
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'

end
